name: Test myCustomAction Workflow

on: [push]

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      - name: Show FS
        run: ls -la
        
      - name: Execute myCustomAction
        uses: ./
