name: Test myCustomAction Workflow

on: [push]

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute myCustomAction
        uses: ./
        with:
          who: Paco
          message: hola a todos
